#! /bin/sh

#######################
###    AUTOSTART    ###
#######################
pgrep -x sxhkd > /dev/null || sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
nitrogen --restore &
~/.config/polybar/launch.sh &
picom &
xsetroot -cursor_name left_ptr &
xset b off &
#xinput --set-prop 9 315 0 &
xset r rate 250 40 &
nm-applet --indicator &
blueman-applet --indicator &
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
/usr/bin/dunst &
setxkbmap -option caps:escape &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 0 &
killall dunst  &
dunst & 


#######################
###	  Workspaces    ###
#######################
bspc monitor -d         
bspc config border_width         2
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true


#######################
###     Border      ###
#######################
# Catpuccin
 # bspc config focused_border_color        "#89b4fa"
 # bspc config normal_border_color         "#2f2f47"
 # bspc config active_border_color         "#89b4fa"
#
# Gruvbox
bspc config focused_border_color        "#689d6a"
bspc config normal_border_color         "#363c3d"
bspc config active_border_color         "#689d6a"

